# Generated by Django 3.0.7 on 2020-08-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=500)),
                ('date', models.DateTimeField(verbose_name='Date')),
            ],
        ),
    ]
