# Generated by Django 3.0.7 on 2020-08-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New', '0002_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default='black', max_length=1400),
        ),
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(default='merc', max_length=1300),
        ),
    ]
