# Generated by Django 3.0.7 on 2020-08-11 17:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('New', '0011_auto_20200811_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 11, 22, 52, 47, 480932), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 11, 22, 52, 47, 481929), verbose_name='Date'),
        ),
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rec', models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sen', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='msg_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
