# Generated by Django 3.0.7 on 2020-08-11 17:58

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('New', '0013_auto_20200811_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='HOLDER',
            field=models.ManyToManyField(related_name='msgcreated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='car',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 11, 23, 28, 52, 352340), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 11, 23, 28, 52, 354351), verbose_name='Date'),
        ),
    ]
