# Generated by Django 3.0.7 on 2020-08-12 07:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('New', '0014_auto_20200811_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 13, 17, 48, 952268), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='msg',
            name='rec',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='msg',
            name='sen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='msg_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 13, 17, 48, 953267), verbose_name='Date'),
        ),
    ]
