# Generated by Django 3.0.7 on 2020-08-12 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New', '0015_auto_20200812_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='urls',
            field=models.URLField(default=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 13, 45, 59, 66185), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 13, 45, 59, 67182), verbose_name='Date'),
        ),
    ]
