# Generated by Django 3.0.7 on 2020-08-22 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New', '0018_auto_20200823_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='diagnosis',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 23, 1, 53, 10, 830986), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 23, 1, 53, 10, 831984), verbose_name='Date'),
        ),
    ]
