# Generated by Django 3.0.7 on 2020-08-22 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New', '0020_auto_20200823_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 23, 1, 59, 55, 620251), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 23, 1, 59, 55, 623244), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 23, 1, 59, 55, 621260), verbose_name='Date'),
        ),
    ]
