# Generated by Django 3.0.7 on 2020-08-22 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New', '0021_auto_20200823_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='report',
            field=models.TextField(default='Nothing..to show no diagnosis please wait'),
        ),
        migrations.AlterField(
            model_name='car',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 23, 2, 12, 44, 350080), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 23, 2, 12, 44, 353070), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 23, 2, 12, 44, 351075), verbose_name='Date'),
        ),
    ]
